media: assets/images
content:
  - name: categories
    label: Catégories
    type: collection
    path: _categories
    filename: "{primary}.md"
    fields:
      - name: title
        label:
          Nom de la catégorie
        type: string
        required: true


  - name: posts
    label: Posts
    type: collection
    path: _posts
    filename: "{year}-{month}-{day}-{primary}.md"
    fields:
      - name: title
        label: Titre
        type: string
        required: true

      - name: category
        label: Catégorie
        type: reference
        options:
          collection: categories
          search: [ fields.title ]
          label: "{fields.title}"
          value: "{fields.title}"
        required: true

      - name: date
        label: Date
        type: date
        required: true
      - name: image
        label: Image
        type: image
      - name: layout
        type: string
        default: "post"
        hidden: true
      - name: body
        label: Contenu
        type: rich-text